### ISSUE TITLE
Implement different normalization techniques in csv data preprocessor

### ISSUE THREAD

**Issue by Ask149** [klarEDA/klar-EDA#16]
### Description
> The implementation can take one or multiple methods. After the implementations of the method(s), the following things are 
   achievable : 
> - Mean Normalisation of features
> - Standardization of features

### Assumptions
> For standardization of features, it is assumed that the data is in Gaussian Distribution

### Input 
> 1. DataFrame

### Output

> Processed data according to the method. After Standardization or Normalisation.

**Comment by ashish-hacker** [comment]
### Description
> The implementation can take one or multiple methods. After the implementations of the method(s) , the following things are 
   achievable : 
> - Mean Normalisation of features
> - Standardization of features

### Assumptions
> For standardization of features, it is assumed that the data is in Gaussian Distribution

### Input 
> 1. DataFrame

### Output

> Processed data according to the method. After Standardization or Normalisation.

**Comment by Ask149** [comment]
Thank you for the update @ashish-hacker! Please reach out to us at contact.klareda@gmail.com, and we will discuss this further.

**Comment by ashish-hacker** [comment]
Thanks @Ask149 . I will do the same .
