### ISSUE TITLE
Add documentation for the implemented methods in csv data visualizer

### ISSUE THREAD

**Issue by Ask149** [klarEDA/klar-EDA#19]
**Description**  

> Document the methods present in the `csv_visualize.py` abiding by the [Sphinx Documentation](https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html) examples

**Comment by rubyruins** [comment]
Hi, I'd like to work on this issue for GSSOC. Could you please assign it to me?

**Comment by Ask149** [comment]
Thank you for your interest @rubyruins! Assigning you the issue. Please reach out to us at contact.klareda@gmail.com for further clarification.

**Comment by hritikchaturvedi11** [comment]
I would like to work on this issue.

**Comment by Ask149** [comment]
@hritikchaturvedi11, thank you for your interest. Currently, we are restricting one issue per student. We will be adding more issues shortly. You can additionally try adding your own issues by referring to the generic issues which can be assigned to you.

**Comment by lekshmissunil** [comment]
Hey, I'm a GSSOC'21 participant and would like to work on this. @Ask149  Could you please assign this to me?

**Comment by Ask149** [comment]
Hi @lekshmissunil, Could you please join the Slack channel - [`here`](https://join.slack.com/t/klareda/shared_invite/zt-ndytbmnq-ARgpyJLPMbeFyYo87jrTjA). We can finalize the requirement and timeline of the issue.

**Comment by lekshmissunil** [comment]
I've created a pull request. @Ask149 Please review it asap
