### ISSUE TITLE
Add documentation for the implemented methods in image data visualizer

### ISSUE THREAD

**Issue by Ask149** [klarEDA/klar-EDA#21]
**Description**

> Document the methods present in the `image_visualize.py` abiding by the [Sphinx Documentation](https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html) examples

**Comment by Sibasish-Padhy** [comment]
hello I am gssoc participant 2021 and would like to contribute to this issue...can u please assign me with this issue??

**Comment by Ask149** [comment]
Thank you for your interest @Sibasish-Padhy.

**Comment by Ask149** [comment]
Please email us on contact.klareda@gmail.com for more details and discussion regarding the implementation.

**Comment by Sibasish-Padhy** [comment]
thank you @Ask149

**Comment by Sibasish-Padhy** [comment]
can u gimme the deadline for the pr??@Ask149

**Comment by Ask149** [comment]
@Sibasish-Padhy drop us an email, where we will discuss the rest of the details.

**Comment by Sibasish-Padhy** [comment]
hello sir,I am Sibasish Padhy a participant of gssoc 2021 contributing to
your project on a beginner friendly issue (documentation of functions used
in image visualize.py).Can u tell me about the deadline for submitting the
pr and also what to include in the documentation
