### ISSUE TITLE
Adding Contributor section in readme  ( Automatically )

### ISSUE THREAD

**Issue by rohank2502** [klarEDA/klar-EDA#24]
I will like to add a feature this will update contributor list in read me automatically !! Will start to work on this issue as soon as i get assigend !!

**Comment by Ask149** [comment]
Hi @rohank2502, it seems like a good suggestion. We would like to discuss your approach prior to the implementation. Could you please drop an email at contact.klareda@gmail.com?

**Comment by rohank2502** [comment]
> 
> 
> Hi @rohank2502, it seems like a good suggestion. We would like to discuss your approach prior to the implementation. Could you please drop an email at [contact.klareda@gmail.com](mailto:contact.klareda@gmail.com)?

![628](https://user-images.githubusercontent.com/76584243/111140783-be619c00-85a8-11eb-9555-2c13717c00cb.png)


My work Sample

**Comment by Ask149** [comment]
@rohank2502 We would like to keep this as a future enhancement and not something we require currently.
