### ISSUE TITLE
add contributing.md

### ISSUE THREAD

**Issue by khareyash05** [klarEDA/klar-EDA#26]
Hi ! I would like to create a file named contributing.md which will
Add the following -

1.Difference between GIT and GITHUB
2.How to clone,fork repository
3.How to create a branch and then use git push to push to repo
4.Create a PR
5.Squash commits in a single issue into one
6, Updating the forked and local repo as the updations are made in the upstream
I would like to work on this as a part of GSSOC'21

**Comment by prathimacode-hub** [comment]
Hey, I'm a GSSOC21 participant. I would like to work on this issue. Can you assign it to me?

**Comment by khareyash05** [comment]
@prathimacode-hub I myself am a participant and I have opened the issue for myself
Sorry!

**Comment by prathimacode-hub** [comment]
Ok

**Comment by Ask149** [comment]
@khareyash05 Thank you for your interest. Unfortunately, we are currently restricting the contribution.md to be updated by the mentors/project owners only. We will be adding more issues shortly. You can additionally try adding your other own issues by referring to the generic issues which can be assigned to you.
