### ISSUE TITLE
Update README file

### ISSUE THREAD

**Issue by ANSHIKA1806** [klarEDA/klar-EDA#37]
@ashish-hacker @harshasridhar @ishaanballal21 @rishabh-me 
README is the first file one should read when starting a new project. It's a set of useful information about a project, and a kind of manual. A README text file appears in many various places and refers not only to programming. So i want to make your README file more meaningful and more easier to understand the whole project.

**Comment by ANSHIKA1806** [comment]
@ashish-hacker @harshasridhar @ishaanballal21 @rishabh-me
please assign this task to me , I would love to contribute in your organization

**Comment by Ask149** [comment]
@ANSHIKA1806, You can join our  [Slack](https://join.slack.com/t/klareda/shared_invite/zt-ndytbmnq-ARgpyJLPMbeFyYo87jrTjA)  channel to discuss further. Before assigning we would like to understand what exactly do you plan on adding to the readme.

**Comment by Ask149** [comment]
Not required.
