### ISSUE TITLE
To add contributor's name in README.md file.

### ISSUE THREAD

**Issue by akshatvirmani** [klarEDA/klar-EDA#38]
**Is your feature request related to a problem? Please describe.**

To add contributor's name in README.md file.

**Comment by akshatvirmani** [comment]
I would like to work on this issue. Kindly assign this to me.

**Comment by Ask149** [comment]
Hi @akshatvirmani, thank you for raising the issue. Unfortunately, we do not require the same at this present moment. And hence, marking as the future requirement.
